### ISSUE TITLE
netstandard / project.json support

### ISSUE THREAD

**Issue by jahmai-ca** [MiloszKrajewski/LibZ#13]
I'm not quite sure which is causing this error, but I have a netstandard 1.3 project that I want to libz in some dependencies and I get this error:

4>  
4>  LibZ 1.2.0.0, Copyright (c) 2013-2014, Milosz Krajewski
4>  https://libz.codeplex.com/
4>  
4>  
4>  Executing inject-dll (Injects .dll file into assembly as resource):
4>  
4>  Loading 'C:\xxxx.dll'
4>  Loaded 'xxxx, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
4>  ArgumentException: Assembly 'xxxx, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not reference any known core assembly. Cannot determine .NET version.
4>     at LibZ.Msil.MsilUtilities.GetFrameworkVersion(AssemblyDefinition assembly)
4>     at LibZ.Tool.Tasks.TaskBase.ValidateAsmZInstrumentation(AssemblyDefinition assembly)
4>     at LibZ.Tool.Tasks.InjectDllTask.Execute(String mainFileName, String[] includePatterns, String[] excludePatterns, String keyFileName, String keyFilePassword, Boolean overwrite, Boolean move)
4>     at LibZ.Tool.Commands.InjectDllCommand.Run(String[] remainingArguments)
4>     at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
4>     at LibZ.Tool.Program.Run(String[] args)

**Comment by jahmai-ca** [comment]
https://github.com/MiloszKrajewski/LibZ/pull/14

**Comment by MiloszKrajewski** [comment]
Did you try it? I think as .net core does not have AppDomain it will actually not work. Yes it pack all the assemblies without even blinking, but the result executable will just not work. 
Or I'm missing something?

**Comment by jahmai-ca** [comment]
I never took it any further than reporting the issue, sorry. Ended up using ILRepack.
