### ISSUE TITLE
libz embed native resources?

### ISSUE THREAD

**Issue by axe-usat** [MiloszKrajewski/LibZ#20]
if the dlls are managed and the program native too libz will work managed files?

**Comment by MiloszKrajewski** [comment]
I'm not sure what you are really asking, but I can guess you would like to embed native .dlls, and the answer is... (drum roll) NO, unfortunately you can't. LibZ works on premise that `ResolveAssembly` event is raised when assembly is needed. This even is not raised for native dlls.
