### ISSUE TITLE
clarification in matrix?

### ISSUE THREAD

**Issue by SimonCropp** [MiloszKrajewski/LibZ#29]
> The standard approach to LibZ does alter compiled assemblies (so it should be 'No' like the others). There is a way, though, requiring dropping one file into a project to avoid post-processing completely.

what does this mean? do u get to control at build time what assemblies are merged? or is it about reading a file from disk if it exists?

**Comment by MiloszKrajewski** [comment]
No. It is about you manually including one .cs file in your project. Use [LibZ.Source](https://www.nuget.org/packages/LibZ.Source/)

**Comment by SimonCropp** [comment]
ok

**Comment by MiloszKrajewski** [comment]
Did I misrepresented something in Costura.Fody column? Happy to fix (I've created this matrix so long time ago, that it might no longer accurate).

**Comment by SimonCropp** [comment]
nah dont worry about it. was just curious
