### ISSUE TITLE
Hidden executable?

### ISSUE THREAD

**Issue by dspwhite** [MiloszKrajewski/LibZ#3]
I downloaded the zip, and extracted it, but could not find the whereabouts of the main libz executable. I'm guessing it needs to be compiled, but that could be an adventure in itself (opening the sln file requires a later version of VS than what I have). It would be so handy if you could simply supply the exe along with your project.

Nuget also crashes when I try to download that, so I'm at a loss here. Any thoughts?

**Comment by MiloszKrajewski** [comment]
Why nuget is crashing? When? How? This is not a statement to take lightly.
And executable can be also found on page: https://github.com/MiloszKrajewski/LibZ/releases

**Comment by dspwhite** [comment]
Nuget crashes as soon a I open the main download on the home page. On inspection, it looks like Nuget requires VS 2013 or later (I only have 2010). The home page makes no point of that though.

Many thanks for the LibZ link - it was there under 'Releases' on your home page all the time, though a slightly more prominent location would have been appreciated, especially a direct link to the libz-1.2.0.0-tool.zip :)

Thanks for a great tool btw! It works when merging my main exe with an obfuscated DLL when ILMerge didn't.
