### ISSUE TITLE
Issue with Devexpress Themes

### ISSUE THREAD

**Issue by benoitben** [MiloszKrajewski/LibZ#4]
Hi,
I have Build a Devexpress.libz container and used "Scenario 6: Using source only approach" for registering this file.

When I apply a devexpress theme for the whole application (using ThemeManager.ApplicationThemeName = Theme.Office2010BlueName; for example),
I have a strange behavior: any control loaded after this instruction will not have the chosen theme applied on it (but the default theme).

**Comment by MiloszKrajewski** [comment]
That's me only guessing but some libraries don't load dlls using Resolver but use Assembly.LoadFile(...). Especially, the extensions (like plugins or themes). In such cases there is nothing for LibZ to handle, they want a file so that's what they need to be provided.
Can you isolate dll which contains this particualar theme and not include it?

**Comment by benoitben** [comment]
Many thanks for your reply Mr. Krajewski,
I have isolated dlls witch contains themes, but the problem persists.

**Comment by benoitben** [comment]
I have another question: how can I use Doboz as codec ? 
I had this exception when I launched it using this command :
libz add --libz Devex.libz --include  Devex/*.dll --codec doboz
ArgumentException: Unknown codec name: 'Doboz'

**Comment by MiloszKrajewski** [comment]
I removed all other codecs (apart from deflate) as nobody (including me) was using me and they were just a hassle. So there is no support. Did I forget update documentation?

**Comment by MiloszKrajewski** [comment]
Can you build mini sample application with DevExpress and themes so I can try to debug it? (Not promising anything though)

**Comment by benoitben** [comment]
Hi Mr. Miloz

Please find attached a sample (https://www.dropbox.com/s/09g4tcb7s0zhro1/Libz1.rar?dl=0), it contains:
1. Source code
2. Executable with Libz: in order to generate all.libz, you need to run
libz add --libz all.libz --include  Without Libz/*.dll --codec deflate
3.  Executable without Libz
4. Screen shots demonstrating the issue

Many thanks in any case

**Comment by MiloszKrajewski** [comment]
I just ran it and it seems that themes work fine on main window? Right? Actually, the also work fine on this "scheduler" window, just not all of them. Can you confirm that? Or for you it does not work at all?
I can see main windows switching theme every time I change value in dropdown. Which one, in your opinion, definitely doesn't work?

**Comment by benoitben** [comment]
When you run it you click directly on open scheduler: you will see that the Office2010Blue is not applied on the scheduler.

Also please test it on a machine where Devexpress is not installed

**Comment by MiloszKrajewski** [comment]
It's not a final response (I'll check and recheck) but it seems fine if container is built with `--safe-load` option, for example:

```
libz add --libz all.libz --include *.dll --safe-load
```

NOTE: `--safe-load` forces assemblies to be saved on disk before loading them up (instead just loading them from memory). There must be some problems with fusion (see [here](http://www.hanselman.com/blog/BackToBasicsUsingFusionLogViewerToDebugObscureLoaderErrors.aspx)) . I might make `--safe-load` a default.
NOTE: I wouldn't always trust that Application.OnStartup is soon enough.

Please let me know if it helps.

**Comment by benoitben** [comment]
Many thanks Mr. Milosz, --safe-load resolved this issue.
Please make it default, maybe it will save other developers hours of work.
Libz is a great tool.
