### ISSUE TITLE
Need an option to create temporary assemblies for applications that require assemblies to be physical present on disk?

### ISSUE THREAD

**Issue by ravibpatel** [MiloszKrajewski/LibZ#7]
I am using CompileAssemblyFromSource to compile some code at run time and it requires to have referenced assemblies to be present on disk.  Embedding assemblies using Libz made the application crash because of it. Is there any way to set Libz to create temporary assemblies like Costura.Fody does?

**Comment by MiloszKrajewski** [comment]
'--safe-load' option, available in [scenarios 2-7](https://github.com/MiloszKrajewski/LibZ/blob/master/doc/scenarios.md)

**Comment by ravibpatel** [comment]
Thanks. It does the trick.
