### ISSUE TITLE
Use PDB files in production while still embedding container inside the assembly.

### ISSUE THREAD

**Issue by ravibpatel** [MiloszKrajewski/LibZ#8]
I want to use the pdb file in production. I successfully done that with Scenario 6. But I want to embed the container inside an assembly and still able to use pdb file. is it possible?

**Comment by MiloszKrajewski** [comment]
PDB files are coupled with DLLs, any change to DLL invalidates PDB. And "instrumentation" does change DLL therefore PDBs are invalidated. It's not impossible to fix PDB (some software does it) but I don't know how. Therefore: scenario 6 only for you.

**Comment by ravibpatel** [comment]
I am using crash reporting functionality in my applications So I want only my main executable PDB to work as normal. That way I can get line numbers in the crash.

**Comment by MiloszKrajewski** [comment]
Maybe I wasn't clear and I wanted to give you some background "why". So without getting into details: scenario 6 is the only non-intrusive one. The other scenarios are intrusive and break  DLL/PDB consistency.
